### PR TITLE
Fix modal responsive

### LINKED ISSUE #150: Fix search modal overflow in mobile view
image

### PR DESCRIPTION
**Pull request by Xaconi**
## Description

Closes #150  issue

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings

### CODE REVIEW

File: src/components/Common/Search/GlobalSearchBar.tsx [hunk 1]
```diff
@@ -62,86 +62,84 @@ const GlobalSearchBar: FC<Props> = ({ onSearchResults }) => {
...
-    <div className="w-96">
-      <div ref={resultsRef}>
-        <div className="relative mt-1">
-          <div className="relative w-full overflow-hidden border border-gray-200 cursor-default dark:border-gray-800 rounded-xl sm:text-sm">
-            <input
-              className="w-full py-2 pl-3 pr-10 text-sm bg-transparent focus:outline-none"
-              onChange={(event) => setKeyword(event.target.value)}
-              placeholder="Search by hashtag / channel"
-              value={keyword}
+    <div ref={resultsRef}>
```
Comment (sasicodes) [inline src/components/Common/Search/GlobalSearchBar.tsx:65]: The width is added to have fixed width on the header. Removing it will misalign the positioning.

You can use tailwind breakpoints to just have the width on bigger screens. (`md:w-96`)

Comment (Xaconi) [reply src/components/Common/Search/GlobalSearchBar.tsx]: You're right! Resolved on the last commit!

**Review by sasicodes — APPROVED** [review]
LGTM!
