### PR TITLE
Fixed ambiguously written arrow function and formatting

### LINKED ISSUE #160: (JS-0229) Found an arrow function that could be confused for a comparison
## Description
Arrow functions (`=&gt;`) are similar in syntax to some comparison operators (`&gt;`, `&lt;`, `&lt;=`, and `&gt;=`). This rule warns against using the arrow function syntax in places where it could be confused with a comparison operator.

## Occurrences
There is 1 occurrence of this issue in the repository.

See all occurrences on DeepSource &rarr; [deepsource.io/gh/lenstube-xyz/lenstube/issue/JS-0229/occurrences/](https://deepsource.io/gh/lenstube-xyz/lenstube/issue/JS-0229/occurrences/)

### PR DESCRIPTION
**Pull request by utsav82**
## Description

Closes #160 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Minor changes in old functionality

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings

### CODE REVIEW

File: src/components/Common/VideoCard/VideoOptions.tsx [hunk 1]
```diff
@@ -83,11 +83,11 @@ const VideoOptions = ({
           </button>
           <button
             type="button"
-            onClick={() =>
+            onClick={() => {
```
Comment (sasicodes) [inline src/components/Common/VideoCard/VideoOptions.tsx:86]: can you quick function in the same file?

Comment (utsav82) [reply src/components/Common/VideoCard/VideoOptions.tsx:86]: Can you please elaborate that?
The issue was that arrow function was written along with ternary which could be confusing so I added braces as the possible solution suggested by deepsource.io

Comment (sasicodes) [reply src/components/Common/VideoCard/VideoOptions.tsx:86]: What you did is good. It can be a function that does the same logic rather than having it inside jsx.

Comment (sasicodes) [reply src/components/Common/VideoCard/VideoOptions.tsx:86]: something like `onClick={() => onClickWatchLater()}`

Comment (utsav82) [reply src/components/Common/VideoCard/VideoOptions.tsx:86]: Sure i would do it

File: src/components/Common/VideoCard/VideoOptions.tsx [hunk 2]
```diff
@@ -54,7 +54,11 @@ const VideoOptions = ({
       hideVideo({ variables: { request: { publicationId: video?.id } } })
     }
   }
-
+  function onClickWatchLater() {
```
Comment (sasicodes) [inline src/components/Common/VideoCard/VideoOptions.tsx:57]: can be a arrow function to follow uniformity and line spaces above and below function is appreciated 🙇🏻

Comment (utsav82) [reply src/components/Common/VideoCard/VideoOptions.tsx]: Sorry I'll change it right away

**Review by sasicodes — APPROVED** [review]
Deadpool LGTM
